#!/bin/bash

# Get Linux OS Information
. ./shared

LOGIT "Running Script 'webdna-download'"

# Download, verify and unzip a file
DVU(){

}

# Defaults
LOGIT_LOG="${LOGIT_LOG:-./webdna_download.txt}"
WEBDNA_VERSION="${WEBDNA_VERSION:-8.6.5}"
WEBDNA_FOLDER="${WEBDNA_FOLDER:-WebDNA-folder-8.6}"
LINUX_WEBDNA="${LINUX_WEBDNA:-WebDNA-Linux-FastCGI-$WEBDNA_VERSION}"
ALPINE_WEBDNA="${ALPINE_WEBDNA:-WebDNA-Alpine-FastCGI-$WEBDNA_VERSION}"

# Check for OS
DOWNLOAD_VERSION=$LINUX_WEBDNA
if [ "$ID" = "centos" ] && ([ "$VERSION_ID" = "7" ] || [ "$VERSION_ID" = "8" ]); then
    CPS="rpm -q"
    IPS="yum -y install"
    UPS="yum -y remove"
elif [ "$ID" = "alpine" ]; then
    IPS="apk add"
    UPS="apk del"
    DOWNLOAD_VERSION=$ALPINE_WEBDNA
else
    OS_UNSUPPORTED "$ID $VERSION_ID"
fi

# Begin Downloads
LOGIT "Downloading version $WEBDNA_VERSION of WebDNA!"

# Check for installed packages
LOGIT "Checking for required packages..."
PACKAGE_CHECK "wget"
PACKAGE_CHECK "unzip"

# Download WebDNA Folder
LOGIT "Downloading https://webdna.us/download/$WEBDNA_FOLDER.zip"
wget "https://webdna.us/download/$WEBDNA_FOLDER.zip"

# Check against hash
LOGIT "Verifying $WEBDNA_FOLDER.zip"
sha256sum "$WEBDNA_FOLDER.zip"
if ! sha256sum -c "hashes/$WEBDNA_FOLDER.zip.sha256"; then LOGIT "sha256 Checksum failed for $WEBDNA_FOLDER.zip" >&2; exit 3; fi

# Extract Archive
LOGIT "Extracting $WEBDNA_FOLDER.zip"
unzip -d . "$WEBDNA_FOLDER.zip"

# Remove Archive
LOGIT "Removing $WEBDNA_FOLDER.zip"
rm -f "$WEBDNA_FOLDER.zip"

# Downloaded and verified WebDNA Folder
LOGIT "Downloaded, verified, and extracted $WEBDNA_FOLDER"

# Download WebDNA FCGI
LOGIT "Downloading https://webdna.us/download/$DOWNLOAD_VERSION.zip"
wget "https://webdna.us/download/$DOWNLOAD_VERSION.zip"

# Check against hash
LOGIT "Verifying $DOWNLOAD_VERSION.zip"
sha256sum "$DOWNLOAD_VERSION.zip"
if ! sha256sum -c "hashes/$DOWNLOAD_VERSION.zip.sha256"; then LOGIT "sha256 Checksum failed for $DOWNLOAD_VERSION.zip" >&2; exit 3; fi

# Extract Archive
LOGIT "Extracting $DOWNLOAD_VERSION.zip"
unzip -d . "$DOWNLOAD_VERSION.zip"

# Remove Archive
LOGIT "Removing $DOWNLOAD_VERSION.zip"
rm -f "$DOWNLOAD_VERSION.zip"

# Downloaded and verified WebDNA Folder
LOGIT "Downloaded, verified, and extracted $DOWNLOAD_VERSION"

# Check for version and put together the 'correct' WebDNA Folder Structure

